export const skillsList = [
  'Semantic & accessible HTML',
  'Responsive Web Design',
  'Teamwork',
  'Immutability',
  'Markdown',
  'CSS BEM convention',
  'CSS Grid',
  'CSS flexbox',
  'React Router',
  'Redux-Saga',
  'Redux (Toolkit)',
  'React Hooks',
  'Error handling',
  'Working with API (fetch, axios)',
  'JavaScript: ES6+',
  'Promises, Async/Await',
  'GitHub Pull Requests & Review',
  'Trello',
  'Scrum',
  'NPM',
  'React',
  'GIT',
];

export const nextSkillsList = [
  'React Context',
  'Node.js',
  'Cypress',
  'Unit testing',
  'TypeScript',
  'JS classes',
];
